version: "3"
services:
  web:
    image: broncode_c
    deploy:
      replicas: 40
      resources:
        limits:
          cpus: "0.01"
          memory: 50M
      restart_policy:
        condition: any
    ports:
      - "4000:4000"
    networks:
      - broncode_cnet
networks:
  broncode_cnet:
