version: "3"
services:
  c_service:
    image: broncode_c
    deploy:
      replicas: 30
      resources:
        limits:
          cpus: "0.01"
          memory: 50M
      restart_policy:
        condition: any
    ports:
      - "4000:4000"
    networks:
      - cnet
networks:
  cnet:
