version: "3"
services:
  web:
    image: broncode_c
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "6969:6969"
    networks:
      - webnet
networks:
  webnet:
