version: "3"
services:

  c_service:
    image: broncode_c
    deploy:
      replicas: 30
      resources:
        limits:
          cpus: "0.01"
          memory: 50M
      restart_policy:
        condition: any
    ports:
      - "4000:4000"
    networks:
      - cnet

  python_service:
    image: broncode_python
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.01"
          memory: 50M
      restart_policy:
        condition: any
    ports:
      - "4001:4001"
    networks:
      - pythonnet


  r_service:
    image: broncode_r
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.01"
          memory: 50M
      restart_policy:
        condition: any
    ports:
      - "4002:4002"
    networks:
      - rnet

networks:
  cnet:
  pythonnet:
  rnet:
