# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Copy the current directory contents into the container at /app
COPY . /

# Make port 80 available to the world outside this container
EXPOSE 80

# Run start.py when the container launches
CMD ["python", "start.py"]
