version: "3"
services:
    broncode:
        image: broncode
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.05"
                    memory: 64M
            restart_policy:
                condition: on-failure
        ports:
            - 50000:44455
        networks:
            - webnet
networks:
    webnet:
