# Generated by Django 2.2.5 on 2019-10-11 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('example_code', models.CharField(blank=True, max_length=10000)),
                ('compiler_flags', models.CharField(blank=True, max_length=512)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(default='', max_length=254)),
                ('completed_lessons', models.ManyToManyField(blank=True, to='poc.Lesson')),
                ('enrolled_in', models.ManyToManyField(blank=True, to='poc.Course')),
                ('owned', models.ManyToManyField(blank=True, related_name='owned_courses', to='poc.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poc_userprofile',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10000)),
                ('compiler_flags', models.CharField(max_length=512)),
                ('passed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.Lesson')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.CharField(max_length=2048)),
                ('stdout', models.CharField(max_length=2048)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.Course'),
        ),
    ]
