# Generated by Django 2.2.5 on 2019-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='user',
            name='enrolled_in',
            field=models.ManyToManyField(null=True, to='poc.Course'),
        ),
    ]
