# Generated by Django 2.2.5 on 2019-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0002_auto_20190926_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='poc.Lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrolled_in',
            field=models.ManyToManyField(blank=True, to='poc.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owned',
            field=models.ManyToManyField(blank=True, related_name='owned_courses', to='poc.Course'),
        ),
    ]
