# Generated by Django 2.2.5 on 2019-09-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0003_auto_20190926_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='compiler_flags',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='example_code',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.CharField(max_length=10000),
        ),
    ]
